"""empty message

Revision ID: 10c876b7e322
Revises: 
Create Date: 2023-06-15 16:44:28.261530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c876b7e322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bolsista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_filekey', sa.String(), nullable=True))
        batch_op.drop_column('foto_perfil_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bolsista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_key', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('foto_perfil_filekey')

    # ### end Alembic commands ###
