"""empty message

Revision ID: e03de7825d84
Revises: 10c876b7e322
Create Date: 2023-06-15 17:10:31.568459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03de7825d84'
down_revision = '10c876b7e322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('id_bolsista', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('id_foto_especime', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_bolsista'], ['especime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especime')
    # ### end Alembic commands ###
